/* Generated by scripts/generate-book-image-index.js. Do not edit. */
(function (global) {
  global.BOOK_IMAGE_INDEX = Object.freeze({
  "el-caballo-y-el-muchacho": [
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 14,
      "imageId": "image-001",
      "description": "Un jinete sobre su caballo, dos hombres arrodillados a la derecha. Objetos esparcidos en el suelo.",
      "audio": "el-caballo-y-el-muchacho/audios/page-014/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 43,
      "imageId": "image-001",
      "description": "Shasta cabalga desesperadamente mientras Aslan lo persigue de cerca, mostrando únicamente su cabeza y su gran melena",
      "audio": "el-caballo-y-el-muchacho/audios/page-043/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 50,
      "imageId": "image-001",
      "description": "Aravis, con casco puntiagudo relata una historia. Armaduras, armas y huesos esparcidos a su alrededor.",
      "audio": "el-caballo-y-el-muchacho/audios/page-050/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 58,
      "imageId": "image-001",
      "description": "Un rey conversa con una doncella, un mercader prepara sus provisiones, un jinete parte a caballo, una pareja celebra con música y otro caballero continúa el viaje.",
      "audio": "el-caballo-y-el-muchacho/audios/page-058/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 59,
      "imageId": "image-001",
      "description": "Una doncella yace dormida por las drogas, mientras un jinete cabalga velozmente y otro continúa su viaje a caballo entre las montañas.",
      "audio": "el-caballo-y-el-muchacho/audios/page-059/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 70,
      "imageId": "image-001",
      "description": "La inmensa ciudad amurallada de Tashbaan asciende en terrazas hasta el majestuoso palacio del Tisroc.",
      "audio": "el-caballo-y-el-muchacho/audios/page-070/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 84,
      "imageId": "image-001",
      "description": "Shasta conversando con el señor Tumnus, acompañados por un enano y un cuervo parlante.",
      "audio": "el-caballo-y-el-muchacho/audios/page-084/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 93,
      "imageId": "image-001",
      "description": "La reina Susan bailando con Tumnus, mientras Sallowpad, el cuervo parlante, y las demás aves observan.",
      "audio": "el-caballo-y-el-muchacho/audios/page-093/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 97,
      "imageId": "image-001",
      "description": "Abundancia del banquete con el ave asada, langosta, panes, frutas, fuentes y jarra.",
      "audio": "el-caballo-y-el-muchacho/audios/page-097/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 100,
      "imageId": "image-001",
      "description": "El príncipe Corin entra por la ventana y sorprende a Shasta, quien descubre que el muchacho tiene un rostro idéntico al suyo.",
      "audio": "el-caballo-y-el-muchacho/audios/page-100/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 108,
      "imageId": "image-001",
      "description": "Shasta permanece solo al borde del desierto, frente a las inquietantes tumbas de los antiguos reyes.",
      "audio": "el-caballo-y-el-muchacho/audios/page-108/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 122,
      "imageId": "image-001",
      "description": "Lasaraleen, recostada en una lujosa litera con dosel, es transportada por una comitiva de sirvientes por las calles de Tashbaan.",
      "audio": "el-caballo-y-el-muchacho/audios/page-122/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 130,
      "imageId": "image-001",
      "description": "Aravis y Lasaraleen conversan sentadas entre almohadones en una lujosa habitación de Tashbaan.",
      "audio": "el-caballo-y-el-muchacho/audios/page-130/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 140,
      "imageId": "image-001",
      "description": "El príncipe Rabadash, enfurecido, levanta el pie para patear a un poeta que permanece inclinado en el suelo.",
      "audio": "el-caballo-y-el-muchacho/audios/page-140/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 150,
      "imageId": "image-001",
      "description": "El principe Rabadash, enfurecido, sale a toda prisa de la habitación.",
      "audio": "el-caballo-y-el-muchacho/audios/page-150/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 153,
      "imageId": "image-001",
      "description": "El Tisroc abandona la habitación acompañado por dos sirvientes que iluminan su camino con antorchas.",
      "audio": "el-caballo-y-el-muchacho/audios/page-153/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 167,
      "imageId": "image-001",
      "description": "Shasta y Aravis avanzan montados en Bree y Hwin por un estrecho desfiladero rodeado de enormes paredes rocosas.",
      "audio": "el-caballo-y-el-muchacho/audios/page-167/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 168,
      "imageId": "image-001",
      "description": "Shasta, Aravis, Bree y Hwin se detienen en una laguna entre las montañas para beber y recuperar fuerzas.",
      "audio": "el-caballo-y-el-muchacho/audios/page-168/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 178,
      "imageId": "image-001",
      "description": "Hwin galopa sola, ensillada y con su equipaje, hacia el Ermitaño de la Frontera Sur.",
      "audio": "el-caballo-y-el-muchacho/audios/page-178/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 179,
      "imageId": "image-001",
      "description": "Hwin galopa con Aravis sobre su lomo mientras un león intenta alcanzar sus patas traseras y Shasta observa desde el suelo junto a un árbol.",
      "audio": "el-caballo-y-el-muchacho/audios/page-179/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 192,
      "imageId": "image-001",
      "description": "Shasta corre apresuradamente cuesta arriba por un sendero rocoso, atravesando un bosque de grandes árboles.",
      "audio": "el-caballo-y-el-muchacho/audios/page-192/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 194,
      "imageId": "image-001",
      "description": "El rey Lune escucha el aviso de Shasta y ordena a lord Darrin partir de inmediato, mientras preparan otro caballo para el muchacho.",
      "audio": "el-caballo-y-el-muchacho/audios/page-194/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 211,
      "imageId": "image-001",
      "description": "Shasta se detiene sorprendido en el bosque al encontrarse frente a un gran erizo parlante erguido sobre sus patas traseras.",
      "audio": "el-caballo-y-el-muchacho/audios/page-211/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 220,
      "imageId": "image-001",
      "description": "Edmund y Lucy avanzan a caballo al frente de una comitiva de gigantes, un centauro, perros y un gran oso parlante.",
      "audio": "el-caballo-y-el-muchacho/audios/page-220/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 221,
      "imageId": "image-001",
      "description": "Edmund portando un gran estandarte, seguido muy de cerca por los demás jinetes y un felino parlante.",
      "audio": "el-caballo-y-el-muchacho/audios/page-221/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 231,
      "imageId": "image-001",
      "description": "Los ejércitos de Archenland y Calormen avanzan al encuentro frente al castillo de Anvard, preparándose para la batalla.",
      "audio": "el-caballo-y-el-muchacho/audios/page-231/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-caballo-y-el-muchacho",
      "page": 241,
      "imageId": "image-001",
      "description": "El príncipe Rabadash cae aparatosamente en plena batalla, con los brazos y las piernas abiertos, mientras su escudo yace en el suelo.",
      "audio": "el-caballo-y-el-muchacho/audios/page-241/images/image-001_p1.mp3"
    }
  ],
  "el-principe-caspian": [
    {
      "bookId": "el-principe-caspian",
      "page": 18,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-018/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 23,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-023/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 29,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-029/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 35,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-035/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 41,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-041/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 46,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-046/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 48,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-048/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 52,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-052/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 59,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-059/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 62,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-062/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 67,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-067/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 85,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-085/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 87,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-087/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 96,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-096/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 97,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-097/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 104,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-104/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 108,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-108/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 112,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-112/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 120,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-120/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 121,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-121/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 137,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-137/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 138,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-138/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 151,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-151/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 152,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-152/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 162,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-162/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 165,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-165/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 166,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-166/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 171,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-171/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 179,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-179/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 196,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-196/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 200,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-200/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 201,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-201/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 206,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-206/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 218,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-218/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 227,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-227/images/image-001_p1.mp3"
    },
    {
      "bookId": "el-principe-caspian",
      "page": 235,
      "imageId": "image-001",
      "description": "",
      "audio": "el-principe-caspian/audios/page-235/images/image-001_p1.mp3"
    }
  ],
  "narnia-el-leon-la-bruja-y-el-armario": [
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 13,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-013/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 16,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-016/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 22,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-022/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 23,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-023/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 24,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-024/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 25,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-025/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 26,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-026/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 30,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-030/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 37,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-037/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 39,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-039/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 42,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-042/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 47,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-047/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 60,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-060/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 65,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-065/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 73,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-073/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 77,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-077/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 82,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-082/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 83,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-083/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 90,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-090/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 91,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-091/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 94,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-094/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 105,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-105/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 115,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-115/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 117,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-117/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 118,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-118/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 121,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-121/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 127,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-127/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 138,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-138/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 141,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-141/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 143,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-143/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 147,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-147/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 148,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-148/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 155,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-155/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 168,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-168/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 176,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-176/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 190,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-190/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 194,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-194/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 196,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-196/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 199,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-199/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 210,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-210/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 218,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-218/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 219,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-219/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 224,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-224/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 230,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-230/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-leon-la-bruja-y-el-armario",
      "page": 233,
      "imageId": "image-001",
      "description": "",
      "audio": "narnia-el-leon-la-bruja-y-el-armario/audios/page-233/images/image-001_p1.mp3"
    }
  ],
  "narnia-el-sobrino-del-mago": [
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 11,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY, EN EL JARDÍN TRASERO CONVERSANDO, HAY UN ÁRBOL A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-011/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 15,
      "imageId": "image-001",
      "description": "PIEZA OCULTA, POLLY EN UN RINCÓN CON UN LIBRO, UN COFRE UNA RAQUETA UNA SILLA Y OBJETOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-015/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 19,
      "imageId": "image-001",
      "description": "LOS DOS NIÑOS CON UNA VELA, UNA PUERTA ENTREABIERTA Y UNA SALA CON TELARAÑAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-019/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 31,
      "imageId": "image-001",
      "description": "UN COFRE, TELAARAÑAS ARAÑAS RATAS, UNA ANCIANA EN CAMA UN PEQUEÑO DUENDE",
      "audio": "narnia-el-sobrino-del-mago/audios/page-031/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 34,
      "imageId": "image-001",
      "description": "TÍO ANDREW Y SU SOMBRA, FLACO DESGARBADO, DE FRACK Y DESPEINADO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-034/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 45,
      "imageId": "image-001",
      "description": "DIGORY EN UN BOSQUE, UNA LAGUNA Y UNA NIÑA DURMIENDO JUNTO A UN ÁRBOL",
      "audio": "narnia-el-sobrino-del-mago/audios/page-045/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 47,
      "imageId": "image-001",
      "description": "CONEJILLO DE INDIAS, CON UN MOÑO, SOBRE EL PASTO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-047/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 61,
      "imageId": "image-001",
      "description": "CIUDAD DESTRUIDA, POLLY Y DIGORY PARADOS, ESCOMBROS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-061/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 66,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY A LA IZQUIERDA, MIRANDO UNA FUENTE, UNA FIGURA CON ALAS Y CON LA BOCA ABIERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-066/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 68,
      "imageId": "image-001",
      "description": "VARIAS PERSONAS SENTADAS, REYES Y REINAS, HERMOSOS VESTIDOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-068/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 78,
      "imageId": "image-001",
      "description": "UNA REINA MALVADA, LOS NIÑOS AL CENTRO, LOS REYES SENTADOS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-078/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 81,
      "imageId": "image-001",
      "description": "LA REINA DE LA MANO DE LOS NIÑOS, UNA ESCALERA DE FONDO, SE DERRUMBAN LAS ARCADAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-081/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 83,
      "imageId": "image-001",
      "description": "LA REINA, CON EL BRAZO IZQUIERDO EXTENDIDO, UNA PESADA PUERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-083/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 99,
      "imageId": "image-001",
      "description": "UNA MESA CON ELEMENTOS DE LABORATORIO, TÍO ANDREW INCLINADO, LA BRUJA A LA DERECHA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-099/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 101,
      "imageId": "image-001",
      "description": "LA BRUJA, SOSTENIENDO DE LOS PELOS A TÍO ANDREW, QUE ESTÁ DE ESPALDAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-101/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 103,
      "imageId": "image-001",
      "description": "TÍO ANDREW DE ESPALDAS, ABRE UNA PUERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-103/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 109,
      "imageId": "image-001",
      "description": "TÍA LETTY, COCIENDO UN COLCHÓN, UN VENTANAL DE FONDO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-109/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 121,
      "imageId": "image-001",
      "description": "UN COCHE A CABALLO, LA BRUJA SOBRE EL TECHO, UN FAROL ATRAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-121/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 123,
      "imageId": "image-001",
      "description": "TÍO ANDREW CON GALERA, TRES OFICIALES A SU IZQUIERDA, UN SEÑOR GORDO MAS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-123/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 124,
      "imageId": "image-001",
      "description": "UN NIÑO EN BICICLETA, CUATRO NIÑOS CORRIENDO A LA IZQUIERDA Y UN PERRO, TRES PERSONAS CORRIENDO DETRAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-124/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 139,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY MIRANDO EL AMANECER, A LA IZQUIERDA EL CABALLO Y EL COCHERO, MÁS A LA IZQUIERDA LA BRUJA Y EL TÍO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-139/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 147,
      "imageId": "image-001",
      "description": "ASLAN BAJANDO UNA COLINA, UN ARBUSTO CON POCAS HOJAS A LA IZQUIERDA, UN ÁRBOL A LA DERECHA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-147/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 154,
      "imageId": "image-001",
      "description": "UNA PEQUEÑA MADRIGUERA DE TOPO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-154/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 155,
      "imageId": "image-001",
      "description": "UNA MADRIGUERA DONDE NACE UN CIERVO, A LA IZQUIERDA DOS PERROS, A LA DERECHA UN TOPO Y UN AVE VOLANDO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-155/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 155,
      "imageId": "image-002",
      "description": "UNA MADRIGUERA CON DOS TOPOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-155/images/image-002_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 157,
      "imageId": "image-001",
      "description": "UN ELEFANTE, MARIPOSAS Y UN TIGRE",
      "audio": "narnia-el-sobrino-del-mago/audios/page-157/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 158,
      "imageId": "image-001",
      "description": "ASLAN AL CENTRO, ALREDEDOR PAREJAS DE ANIMALES; ELEFANTES, JIRAFAS, CABALLOS, RENOS, CEBRAS, CIERVO, AVES, PERROS, TOPOS, MARIPOSAS, TIGRES",
      "audio": "narnia-el-sobrino-del-mago/audios/page-158/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 163,
      "imageId": "image-001",
      "description": "UNA JOVEN CON UNA CORONA DE LAURELES,  GRANJERO PEQUEÑO, 2 FAUNOS A SUS LADOS, UN CUERVO Y UN CONEJO. UN ÁRBOL DETRÁS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-163/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 164,
      "imageId": "image-001",
      "description": "ROBLE, BÚHO, 2 CUERVOS, JEFE ENANO; ELEFANTE Y DIOS DEL RÍO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-164/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 174,
      "imageId": "image-001",
      "description": "TÍO ANDREW CON GALERA, LEOPARDO A LA CARRERA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-174/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 175,
      "imageId": "image-001",
      "description": "ALCE, ELEFANTE, OSOS, JABALÍES, PANTERAS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-175/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 178,
      "imageId": "image-001",
      "description": "TÍO ANDREW EN EL SUELO, ARBUSTO ATRÁS, JABALÍ, CUERVO; BURRO, OSO TUMBADO DE ESPALDA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-178/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 183,
      "imageId": "image-001",
      "description": "UNA FIGURA EXTRAÑA ES REGADA POR UN ELEFANTE; OSO, JABALÍ, CUERVO Y OTROS ANIMALES.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-183/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 189,
      "imageId": "image-001",
      "description": "EL CABALLERO CON SOMBRERO BOMBÍN, UNA JOVEN DEL BRAZO, UN ÁRBOL A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-189/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 198,
      "imageId": "image-001",
      "description": "SECUENCIA DE 5 CABALLOS AL QUE LE SALEN ALAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-198/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 202,
      "imageId": "image-001",
      "description": "CABALLO ALADO, CON POLLY Y DIGORY AL LOMO, VOLANDO SOBRE UNA CASCADA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-202/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 207,
      "imageId": "image-001",
      "description": "CABALLO ALADO CUBRIENDO CON UN ALA A UN NIÑO.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-207/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 213,
      "imageId": "image-001",
      "description": "CABALLO ALADO CON LOS NIÑOS VOLANDO, MONTAÑAS NEVADAS AL REDEDOR, VALLES VERDES DEBAJO.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-213/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 217,
      "imageId": "image-001",
      "description": "ÁRBOL DE MANZANAS PLATEADAS, DIGORY A LA DERECHA, SOBRE EL ÁRBOL UN AVE MAJESTUOSA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-217/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 230,
      "imageId": "image-001",
      "description": "TÍO ANDREW EN EL MEDIO DE UNA ENRRAMADA COMO UN NIDO, UNA PALOMA ARRIBA, 3 ARDILLAS TIRANDOLE BELLOTAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-230/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 235,
      "imageId": "image-001",
      "description": "2 ENANOS FUNDIENDO ORO, 2 CHICOS CORTANDO RAMAS DE UN ÁRBOL A LA IZQUIERDA, 1 ENANO FORJANDO UNA CORONA A LA DERECHA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-235/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 237,
      "imageId": "image-001",
      "description": "REY Y REINA CORONADOS POR ASLAN, NIÑOS Y ANIMALES ASISTIENDO A LA CEREMONIA, UN ÁRBOL FRONDOZO DETRÁS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-237/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 246,
      "imageId": "image-001",
      "description": "LA MADRE DE DIGORY EN LA CAMA CON UN LIBRO EN EL REGAZO, DIGORY LE DA DE COMER UNA MANZANA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-246/images/image-001_p1.mp3"
    }
  ]
});
  if (typeof module !== "undefined" && module.exports) module.exports = global.BOOK_IMAGE_INDEX;
})(typeof window !== "undefined" ? window : globalThis);
