/* Generated by scripts/generate-book-image-index.js. Do not edit. */
(function (global) {
  global.BOOK_IMAGE_INDEX = Object.freeze({
  "narnia-el-leon-la-bruja-y-el-armario": [],
  "narnia-el-sobrino-del-mago": [
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 11,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY, EN EL JARDÍN TRASERO CONVERSANDO, HAY UN ÁRBOL A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-011/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 15,
      "imageId": "image-001",
      "description": "PIEZA OCULTA, POLLY EN UN RINCÓN CON UN LIBRO, UN COFRE UNA RAQUETA UNA SILLA Y OBJETOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-015/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 19,
      "imageId": "image-001",
      "description": "LOS DOS NIÑOS CON UNA VELA, UNA PUERTA ENTREABIERTA Y UNA SALA CON TELARAÑAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-019/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 31,
      "imageId": "image-001",
      "description": "UN COFRE, TELAARAÑAS ARAÑAS RATAS, UNA ANCIANA EN CAMA UN PEQUEÑO DUENDE",
      "audio": "narnia-el-sobrino-del-mago/audios/page-031/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 34,
      "imageId": "image-001",
      "description": "TÍO ANDREW Y SU SOMBRA, FLACO DESGARBADO, DE FRACK Y DESPEINADO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-034/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 45,
      "imageId": "image-001",
      "description": "DIGORY EN UN BOSQUE, UNA LAGUNA Y UNA NIÑA DURMIENDO JUNTO A UN ÁRBOL",
      "audio": "narnia-el-sobrino-del-mago/audios/page-045/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 47,
      "imageId": "image-001",
      "description": "CONEJILLO DE INDIAS, CON UN MOÑO, SOBRE EL PASTO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-047/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 61,
      "imageId": "image-001",
      "description": "CIUDAD DESTRUIDA, POLLY Y DIGORY PARADOS, ESCOMBROS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-061/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 66,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY A LA IZQUIERDA, MIRANDO UNA FUENTE, UNA FIGURA CON ALAS Y CON LA BOCA ABIERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-066/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 68,
      "imageId": "image-001",
      "description": "VARIAS PERSONAS SENTADAS, REYES Y REINAS, HERMOSOS VESTIDOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-068/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 78,
      "imageId": "image-001",
      "description": "UNA REINA MALVADA, LOS NIÑOS AL CENTRO, LOS REYES SENTADOS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-078/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 81,
      "imageId": "image-001",
      "description": "LA REINA DE LA MANO DE LOS NIÑOS, UNA ESCALERA DE FONDO, SE DERRUMBAN LAS ARCADAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-081/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 83,
      "imageId": "image-001",
      "description": "LA REINA, CON EL BRAZO IZQUIERDO EXTENDIDO, UNA PESADA PUERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-083/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 99,
      "imageId": "image-001",
      "description": "UNA MESA CON ELEMENTOS DE LABORATORIO, TÍO ANDREW INCLINADO, LA BRUJA A LA DERECHA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-099/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 101,
      "imageId": "image-001",
      "description": "LA BRUJA, SOSTENIENDO DE LOS PELOS A TÍO ANDREW, QUE ESTÁ DE ESPALDAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-101/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 103,
      "imageId": "image-001",
      "description": "TÍO ANDREW DE ESPALDAS, ABRE UNA PUERTA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-103/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 109,
      "imageId": "image-001",
      "description": "TÍA LETTY, COCIENDO UN COLCHÓN, UN VENTANAL DE FONDO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-109/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 121,
      "imageId": "image-001",
      "description": "UN COCHE A CABALLO, LA BRUJA SOBRE EL TECHO, UN FAROL ATRAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-121/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 123,
      "imageId": "image-001",
      "description": "TÍO ANDREW CON GALERA, TRES OFICIALES A SU IZQUIERDA, UN SEÑOR GORDO MAS A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-123/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 124,
      "imageId": "image-001",
      "description": "UN NIÑO EN BICICLETA, CUATRO NIÑOS CORRIENDO A LA IZQUIERDA Y UN PERRO, TRES PERSONAS CORRIENDO DETRAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-124/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 139,
      "imageId": "image-001",
      "description": "POLLY Y DIGORY MIRANDO EL AMANECER, A LA IZQUIERDA EL CABALLO Y EL COCHERO, MÁS A LA IZQUIERDA LA BRUJA Y EL TÍO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-139/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 147,
      "imageId": "image-001",
      "description": "ASLAN BAJANDO UNA COLINA, UN ARBUSTO CON POCAS HOJAS A LA IZQUIERDA, UN ÁRBOL A LA DERECHA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-147/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 154,
      "imageId": "image-001",
      "description": "UNA PEQUEÑA MADRIGUERA DE TOPO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-154/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 155,
      "imageId": "image-001",
      "description": "UNA MADRIGUERA DONDE NACE UN CIERVO, A LA IZQUIERDA DOS PERROS, A LA DERECHA UN TOPO Y UN AVE VOLANDO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-155/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 155,
      "imageId": "image-002",
      "description": "UNA MADRIGUERA CON DOS TOPOS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-155/images/image-002_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 157,
      "imageId": "image-001",
      "description": "UN ELEFANTE, MARIPOSAS Y UN TIGRE",
      "audio": "narnia-el-sobrino-del-mago/audios/page-157/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 158,
      "imageId": "image-001",
      "description": "ASLAN AL CENTRO, ALREDEDOR PAREJAS DE ANIMALES; ELEFANTES, JIRAFAS, CABALLOS, RENOS, CEBRAS, CIERVO, AVES, PERROS, TOPOS, MARIPOSAS, TIGRES",
      "audio": "narnia-el-sobrino-del-mago/audios/page-158/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 163,
      "imageId": "image-001",
      "description": "UNA JOVEN CON UNA CORONA DE LAURELES,  GRANJERO PEQUEÑO, 2 FAUNOS A SUS LADOS, UN CUERVO Y UN CONEJO. UN ÁRBOL DETRÁS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-163/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 164,
      "imageId": "image-001",
      "description": "ROBLE, BÚHO, 2 CUERVOS, JEFE ENANO; ELEFANTE Y DIOS DEL RÍO",
      "audio": "narnia-el-sobrino-del-mago/audios/page-164/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 174,
      "imageId": "image-001",
      "description": "TÍO ANDREW CON GALERA, LEOPARDO A LA CARRERA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-174/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 175,
      "imageId": "image-001",
      "description": "ALCE, ELEFANTE, OSOS, JABALÍES, PANTERAS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-175/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 178,
      "imageId": "image-001",
      "description": "TÍO ANDREW EN EL SUELO, ARBUSTO ATRÁS, JABALÍ, CUERVO; BURRO, OSO TUMBADO DE ESPALDA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-178/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 183,
      "imageId": "image-001",
      "description": "UNA FIGURA EXTRAÑA ES REGADA POR UN ELEFANTE; OSO, JABALÍ, CUERVO Y OTROS ANIMALES.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-183/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 189,
      "imageId": "image-001",
      "description": "EL CABALLERO CON SOMBRERO BOMBÍN, UNA JOVEN DEL BRAZO, UN ÁRBOL A LA IZQUIERDA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-189/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 198,
      "imageId": "image-001",
      "description": "SECUENCIA DE 5 CABALLOS AL QUE LE SALEN ALAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-198/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 202,
      "imageId": "image-001",
      "description": "CABALLO ALADO, CON POLLY Y DIGORY AL LOMO, VOLANDO SOBRE UNA CASCADA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-202/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 207,
      "imageId": "image-001",
      "description": "CABALLO ALADO CUBRIENDO CON UN ALA A UN NIÑO.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-207/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 213,
      "imageId": "image-001",
      "description": "CABALLO ALADO CON LOS NIÑOS VOLANDO, MONTAÑAS NEVADAS AL REDEDOR, VALLES VERDES DEBAJO.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-213/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 217,
      "imageId": "image-001",
      "description": "ÁRBOL DE MANZANAS PLATEADAS, DIGORY A LA DERECHA, SOBRE EL ÁRBOL UN AVE MAJESTUOSA",
      "audio": "narnia-el-sobrino-del-mago/audios/page-217/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 230,
      "imageId": "image-001",
      "description": "TÍO ANDREW EN EL MEDIO DE UNA ENRRAMADA COMO UN NIDO, UNA PALOMA ARRIBA, 3 ARDILLAS TIRANDOLE BELLOTAS",
      "audio": "narnia-el-sobrino-del-mago/audios/page-230/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 235,
      "imageId": "image-001",
      "description": "2 ENANOS FUNDIENDO ORO, 2 CHICOS CORTANDO RAMAS DE UN ÁRBOL A LA IZQUIERDA, 1 ENANO FORJANDO UNA CORONA A LA DERECHA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-235/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 237,
      "imageId": "image-001",
      "description": "REY Y REINA CORONADOS POR ASLAN, NIÑOS Y ANIMALES ASISTIENDO A LA CEREMONIA, UN ÁRBOL FRONDOZO DETRÁS.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-237/images/image-001_p1.mp3"
    },
    {
      "bookId": "narnia-el-sobrino-del-mago",
      "page": 246,
      "imageId": "image-001",
      "description": "LA MADRE DE DIGORY EN LA CAMA CON UN LIBRO EN EL REGAZO, DIGORY LE DA DE COMER UNA MANZANA.",
      "audio": "narnia-el-sobrino-del-mago/audios/page-246/images/image-001_p1.mp3"
    }
  ]
});
  if (typeof module !== "undefined" && module.exports) module.exports = global.BOOK_IMAGE_INDEX;
})(typeof window !== "undefined" ? window : globalThis);